                                        TUGAS V 
                             'ALGORITMA DAN STRUKTUR DATA'



5.16 List Dua Dimensi

List dua dimensi digunakan untuk menempatkan sebuah list didalam list ,penggambarannya seperti sebuah matrik .

In [ ]:
#inisialisasi variabel daerah
daerah = [
    ['Bali','Jawa Barat','Papua'],
    ['pendet','jaipong','sajojo'],
]
#menampilkan variabel daerah
print(daerah)
#menampilkan elemen pada baris pertama 
print(daerah[0][0] + ' adalah pulau yang sangat indah')
#menampilkan elemen pada garis kedua 
print(daerah[1][0] + ' merupakan tarian dari daerah bali')
#menampilkan elemen pada baris kedua ,kolom ketiga 
print(daerah[1][2] + ' adalah lagu yang berasal dari papua')
#menampilkan elemen pada baris pertama,kolom kedua
print(daerah[0][1] )

[['Bali', 'Jawa Barat', 'Papua'], ['pendet', 'jaipong', 'sajojo']]
Bali adalah pulau yang sangat indah
pendet merupakan tarian dari daerah bali
sajojo adalah lagu yang berasal dari papua
Jawa Barat


In [ ]:
#inisialisasi variabel buah
buah =[
    ['leci','mangga','durian','pisang'],
    ['rambutan','manggis','apel','anggur'],
    ['jeruk','jambu','salak','nanas'],
]
#menampilkan variabel baris ketiga ,kolom ketiga
print(buah [2][2] )
#menampilkan variabel baris pertama ,kolom ketiga
print(buah [0][2] + ' adalah buah yang kulitnya berduri tajam')
#menampilkan variabel baris ketiga
print(buah[2])
#menampilkan variabel baris pertama
print(buah[0])
#menampilkan variabel baris kedua
print(buah[1])
#menghitung panjang variabel buah
print(len(buah))



salak
durian adalah buah yang kulitnya berduri tajam
['jeruk', 'jambu', 'salak', 'nanas']
['leci', 'mangga', 'durian', 'pisang']
['rambutan', 'manggis', 'apel', 'anggur']
3


5.17 Tuples 

daftar nilai yang dipisahkan dengan tanda koma dan tuples menggunakan kurung biasa bukan kurung siku ,tetapi data yang dimiliki merupakan data yang tidak ingin dirubah isinya.

In [ ]:
# membuat tuples dengan variabel lagu_pop
lagu_pop = ( 'sial','komang','sisa rasa','hati-hati dijalan','mesin waktu')
# menampilkan variabel lagu_pop
print(lagu_pop)
print(lagu_pop [1:4])
# mengambil panjang tuple lagu_pop
print(len(lagu_pop))

['sial', 'komang', 'sisa rasa', 'hati-hati dijalan', 'mesin waktu']
['komang', 'sisa rasa', 'hati-hati dijalan']
5


In [ ]:
# membuat tuples 
aku = ('Atik Febriyanti','Br Badung Sibanggede',159,47,19,)
nama,alamat,tb,bb,umur = aku 
# dari setiap variabel akan memiliki nilai dari setiap isi tuples secara berurutan
# variabel nama memiliki nilai dari aku[0]
print('Nama  :', nama)
# variabel alamat memiliki nilai dari aku[1]
print('Alamat:' , alamat)
# variabel tinggi badan memiliki nilai dari aku [2]
print('TB    :' , tb)
# variabel berat badan memiliki nilai dari aku [3]
print('BB    :', bb)
# variabel umur memiliki nilai dari aku[4]
print('Umur  :', umur )

Nama  : Atik Febriyanti
Alamat: Br Badung Sibanggede
TB    : 159
BB    : 47
Umur  : 19


5.18 Dictionaries 

dictionaries digunakan jika datanya berkaitan satu sama lain atau digunakan untuk memetakan sebuah nilai pada data kedalam nilainya,tipe data ini dapat dideklarasikan dengan diawali tanda kurung kerawal.

In [ ]:
# ada 2 tipe data pada dictionaries yaitu: 
# key merupakan nama atribut suatu item pada data dictionary
# value adalah nilai yang disimpan pada suatu atribut
lagu={ 
     'made cenik' : ' Bali',
    'rasa sayange': ' Maluku',
    'sajojo' : ' Papua',
    'anging mamiri': ' Sulawesi Selatan',
    'manuk dadali' : ' Jawa Barat',
     }   
# perulangan untuk menampilkan semua isi
for key in lagu:
  print(key,'=' , lagu[key])

# memanfaatkan operator keanggotaan untuk tipe data dictionaries
print('1.apakah variabel lagu memiliki key made cenik ?')
print('made cenik' in lagu)
print('2.apakah variabel lagu memiliki key jali-jali?')
print('jali-jali' in lagu)


made cenik =  Bali
rasa sayange =  Maluku
sajojo =  Papua
anging mamiri =  Sulawesi Selatan
manuk dadali =  Jawa Barat
1.apakah variabel lagu memiliki key made cenik ?
True
2.apakah variabel lagu memiliki key jali-jali?
False


5.19 Fungsi Dalam Python

Fungsi dalam python dibentuk untuk mebuat perulangan dalam pembuatan program secara manual.

In [21]:
# kata 'def' yang menjadi pertanda bahwa blok kode program adalah sebuah fungsi
# memanfaatkan fungsi dan parameter pada python untuk melakukan perulangan
def congratulation_for (nama):
  print(f'haii {nama}...,congratulatian for' + ' your graduation.')
congratulation_for('Atik')
congratulation_for('Ayu')
congratulation_for('Ajeng')

# memanggil fungsi dengan menggunakan parameter opsional
# yang dimana parameter yang kita andaikan tidak di isi
def tinggi_badan(nama,tb,satuan ='cm'):
  print(f"tinggi badan dari {nama} adalah {tb} {satuan}")
tinggi_badan(" Nina",150,'cm')
tinggi_badan("Tina",158,'cm')
tinggi_badan("Tini",157,'cm')
tinggi_badan("Tono",165,'cm')


haii Atik...,congratulatian for your graduation.
haii Ayu...,congratulatian for your graduation.
haii Ajeng...,congratulatian for your graduation.
tinggi badan dari  Nina adalah 150 cm
tinggi badan dari Tina adalah 158 cm
tinggi badan dari Tini adalah 157 cm
tinggi badan dari Tono adalah 165 cm


5.19.1 Tugas Fungsi Pada Python

tugas fungsi pada python adalah menjalankan perintah dan menampilkan hasil perhitungan.


In [7]:
# mendefinisikan fungsi untuk menghitung luas segitiga
def hitung_luas_segitiga(alas,tinggi):
  luas =(alas * tinggi)/2
  return luas
# memasukan input sesuai dengan soal yang diinginkan
a = float(input("masukan nilai panjang alas segitiga:"))
t = float(input("masukan nilai tinggi segitiga:"))

#memanggil fungsi dan menampilkan hasil print
luas = hitung_luas_segitiga(a,t)
print("luas segitiga adalah :" , luas)
print("maka luas dari segitiga tersebut adalah 32")

masukan nilai panjang alas segitiga:8
masukan nilai tinggi segitiga:8
luas segitiga adalah : 32.0
maka luas dari segitiga tersebut adalah 32


5.20 Numpy

Numpy adalah salah satu library dipython yang memiliki keunggulan dalam perhitungan menggunakan vertor dan matrik dalam berbagai dimensi.

In [7]:
# membuat sebuah array dengan menggunakan numpy
import numpy as np
a = np.array([2,4,8,10,12])
# menghitung mean dari array
mean = np.mean(a)
# mencari nilai maksimum array 
max_val = np.max(a)
# membuat sebuah matrix dengan numpy 
b =np.array([ [2,4], [8,10]])
# mengalikan matrix dengan sebuah skalar 
c = 2*b
# mengalikan 2 matrix
d =np.dot(b,c)

# kemudian kita cetak hasil dengan perintah print 
print("Array a adalah  :",a)
print("Mean dari array a :",mean)
print("Nilai maksimum dari array a:",max_val)
print("Matrix b :",b)
print("Hasil perkalian b dengan skalar 2:",c)
print("Hasil perkalian matrix b dengan matrix c:",d)

Array a adalah  : [ 2  4  8 10 12]
Mean dari array a : 7.2
Nilai maksimum dari array a: 12
Matrix b : [[ 2  4]
 [ 8 10]]
Hasil perkalian b dengan skalar 2: [[ 4  8]
 [16 20]]
Hasil perkalian matrix b dengan matrix c: [[ 72  96]
 [192 264]]


5.20.1 Perintah Dasar Pada NUmpy

In [11]:
import numpy as np
array1 = np.array([5,4,3,2,1])
array2= np.array([10,9,8,7,6])
# penjumlahan pada numpy
result = array1 + array2
print(result)
# pengurangan pada array
result = array2 -array1
print(result)
# perkalian pada array
result = array2 *array1
print(result)

[15 13 11  9  7]
[5 5 5 5 5]
[50 36 24 14  6]


5.20.2 Memanggil Anggota,Kolom dan Baris dengan Numpy

In [2]:
import numpy as np
A = np.array([
    [4,3,2,1],
    [8,7,6,5],
    [12,11,10,9]])
# mengambil elemen dibaris ke-3 dan kolom ke-4
elemen = A[2,3]
print(elemen)
# mengambil seluruh elemen pada baris ke-2
baris_kedua =A[1,:]
print(baris_kedua)
# mengambil seluruh elemen pada kolom ke-3
kolom_ketiga =A[:,3]
print(kolom_ketiga)
# mengambil elemen pada baris ke-2 dari akhir dan kolom terakhir 
elemen = A[-2,-1]
print(elemen)

9
[8 7 6 5]
[1 5 9]
5


5.20.3 Matrix pada numpy

In [1]:
import numpy as np
# membuat sebuah matrix dengan numpy
matrix_y = np.array([[11,12,13],[14,15,16],[17,18,19]])
matrix_z = np.array([[20,21,22],[23,24,25],[26,27,28]])

# melakukan penjumlahan dengan 2 matrix
matrix_sum = matrix_y + matrix_z
# melakukan perkalian dengan 2 matrix mengunakan dot
matrix_mul =np.dot(matrix_y,matrix_z)
# mencetak hasil dengan menggunakan perintah print
print("Matrix Y:")
print(matrix_y)
print("\nMatrix Z:")
print(matrix_z)
print("\nMatrix Y + Matrix Z:")
print(matrix_sum)
print("\nMatrix Y * Matrix Z :")
print(matrix_mul)


Matrix Y:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Matrix Z:
[[20 21 22]
 [23 24 25]
 [26 27 28]]

Matrix Y + Matrix Z:
[[31 33 35]
 [37 39 41]
 [43 45 47]]

Matrix Y * Matrix Z :
[[ 834  870  906]
 [1041 1086 1131]
 [1248 1302 1356]]


5.20.4 Copy pada Numpy

In [10]:
import numpy as np
angka1 =np.array([2,4,6,8,10])
#membuat copy dari angkat1
angka2 =angka1.copy()
# selanjutnya mengubah nilai pada angka1
angka1[3] = 7
# kemudian kita cetak dengan menggunakan perintah print 
print('angka1:',angka1)
print('angka2:',angka2)
print(angka1)
print(angka2)

angka1: [ 2  4  6  7 10]
angka2: [ 2  4  6  8 10]
[ 2  4  6  7 10]
[ 2  4  6  8 10]


5.20.5 Operasi Matematika pada Numpy

In [28]:
import numpy as np
x = np.array([5,6,7])
y = np.array([8,9,10])

# operasi penjumblahan (+) pada numpy
print(x+y*2)
# operasi pengurangan(-) pada numpy
print(y-x)
# operasi perkalian(*) pada numpy
print(x*y*3)
# operasi pembagian (/) pada numpy
print(x**2/2)
# operasi pangkat(**) pada numpy
print(x**3)
# operasi sin,cos,tangen pada numpy
print(np.sin(y-7))
print(np.cos(x-4))
print(np.cos(y-7))

[21 24 27]
[3 3 3]
[120 162 210]
[12.5 18.  24.5]
[125 216 343]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 0.54030231 -0.41614684 -0.9899925 ]


5.20.6 Perkalian Matrix Pada Numpy

In [6]:
import numpy as np
# membuat matrix pertama 
X =np.array([[11,12],
             [14,15]])
# membuat matrix kedua
Y=np.array([[5,6,7],
            [8,9,10]])
# memudian melakukan perkalian antara 2 matrix tersebut 
# dengan menggunakan fungsi 'dot'
# hasil perkalian antar X & Y akan disimpan dalam matrix 'Z'
Z =np.dot(X, Y)
print('Hasil perkalian antara matrix pertama dan kedua adalah :')
print(Z)


Hasil perkalian antara matrix pertama dan kedua adalah :
[[151 174 197]
 [190 219 248]]


5.20.7 Min,Max,dan Sum Pada Numpy

In [5]:
import numpy as np
angka =np.array([10,20,30,40,50])
# menghitung nilai minimun pada 'angka'
print("nilai minumum dari angka adalah:",np.min(angka))
# menghitung nilai Maksimum pada 'angka'
print("nilai maksumum dari angka adalah:",np.max(angka))
# menghitung jumlah elemen yang ada didalam angka 
print ('jumlah elemen dalam angka adalah:',np.sum(angka))

nilai minumum dari angka adalah: 10
nilai maksumum dari angka adalah: 50
jumlah elemen dalam angka adalah: 150
